### ISSUE TITLE
Does this run on a Raspberry Pi?

### ISSUE THREAD

**Issue by jack10768** [bmork/defogger#15]
I'm attempting this on the 8600LH. I managed to install bluepy and Python 3.7. However, when running I get this error:

python dcs8000lh-configure.py 00:11:22:33:44:55 123456 --survey
[real MAC and pin redacted]

Connecting to 00:11:22:33:44:55...
Traceback (most recent call last):
  File "dcs8000lh-configure.py", line 152, in <module>
    cam = BleCam(args.address, args.pincode)
  File "dcs8000lh-configure.py", line 28, in __init__
    self.periph = Peripheral(address)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 00:11:22:33:44:55, addr type: public

Is this because I'm running off a raspberry pi? Is there something else I'm missing? I've checked that the bluetooth agent is on and active and the pi is able to see the reset camera as a bluetooth device.

**Comment by bmork** [comment]
jack10768 <notifications@github.com> writes:

> I'm attempting this on the 8600LH. I managed to install bluepy and Python 3.7. However, when running I get this error:
>
> python dcs8000lh-configure.py 00:11:22:33:44:55 123456 --survey
> [real MAC and pin redacted]
>
> Connecting to 00:11:22:33:44:55...
> Traceback (most recent call last):
>   File "dcs8000lh-configure.py", line 152, in <module>
>     cam = BleCam(args.address, args.pincode)
>   File "dcs8000lh-configure.py", line 28, in __init__
>     self.periph = Peripheral(address)
>   File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 391, in __init__
>     self._connect(deviceAddr, addrType, iface)
>   File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 439, in _connect
>     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
> bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 00:11:22:33:44:55, addr type: public
>
> Is this because I'm running off a raspberry pi? Is there something
> else I'm missing? I've checked that the bluetooth agent is on and
> active and the pi is able to see the reset camera as a bluetooth
> device.



I believe this should work as long as the RPi has BLE support.

Can you connect using e.g gatttool?  See
https://elinux.org/RPi_Bluetooth_LE for an example using RPi.   Running

  hcitool lescan

should show your camere. And

  gatttol -I -b 00:11:22:33:44:55

followed by

 connect
 characteristics

should result in somthing like
  
 # gatttool -I -b 00:11:22:33:44:55 
 [00:11:22:33:44:55][LE]> connect
 Attempting to connect to 00:11:22:33:44:55
 Connection successful
 [00:11:22:33:44:55][LE]> characteristics
 handle: 0x0004, char properties: 0x02, char value handle: 0x0006, uuid: 00002a00-0000-1000-8000-00805f9b34fb
 handle: 0x0007, char properties: 0x02, char value handle: 0x0008, uuid: 00002a01-0000-1000-8000-00805f9b34fb


If this works, then there is some problem with the python script or
libs.  If it doesn't work, then there is some issue with the RPi BLE
support or camera.



Bjørn

**Comment by dave-code-ruiz** [comment]
I have a raspberry and it works perfectly.
I have ever received this message and I think it is a distance or coverage problem.
Unplug the camera and connect it near to the raspberry and try again.
Luck

**Comment by sambal0** [comment]
I´ve got a similar problem and stuck with the recent firmware 2.07.01:

`sudo python dcs8000lh-configure.py 00:11:22:33:44:55 123456 --survey`
[real MAC and pin redacted]

Connecting to 00:11:22:33:44:55...
Verifying IPCam service
Traceback (most recent call last):
  File "dcs8000lh-configure.py", line 152, in <module>
    cam = BleCam(args.address, args.pincode)
  File "dcs8000lh-configure.py", line 29, in __init__
    self._ipcamservice()
  File "dcs8000lh-configure.py", line 38, in _ipcamservice
    except BTLEEException:
NameError: global name 'BTLEEException' is not defined

Tested:
`gatttol -I -b 00:11:22:33:44:55`

it connects to the camera, but doesn´t react to the commands `characteristics` or `primary`.
Any ideas? Thanks a lot in advance.
